// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nccuacxkcxzuhoosdfvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jY3VhY3hrY3h6dWhvb3NkZnZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MzUwNDUsImV4cCI6MjA3MjExMTA0NX0.dPbtOxtQoE0zD1Do1RuZj5myCNqvx1SuSy0neDvZH1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});